### ISSUE TITLE
Can not select bottom task on IphoneX

### ISSUE THREAD

**Issue by Amarsh557** [Charlie9830/pounder#100]
**Describe the bug**
The Bottom/Last task is in the same position at the virtual home button so when trying to select task the app closes, or tries to multitask when swiping for move/copy/delete. You are forced to tap the extreme edges of the task for any operation to occur.

**What were you doing at the time?**
trying to rename task.

**Expected behavior**
task would open to rename.

**Version Information**
 - OS: iOS 12.1.2
 - Version 2.1.0

**Comment by Charlie9830** [comment]
Thanks for the Bug Report.
I am in the process of rebuilding the UI for the Mobile app using a new Component library. I will address this issue in that update in the coming weeks.

**Comment by Charlie9830** [comment]
Also, congratulations. You are the 100th Issue. 💯  💯
