### ISSUE TITLE
After scrolling down new task's name is obstructed

### ISSUE THREAD

**Issue by Amarsh557** [Charlie9830/pounder#101]
**Describe the bug**
After scrolling down occasionally then becoming consistent new task name field will appear to far up the screen and will be obstructed until scrolling up to see it. Does not appear to happen at all after scrolling up the list.

**What were you doing at the time?**
Creating a new task

**Screenshots**
![image1 copy](https://user-images.githubusercontent.com/46048346/50772145-b927a900-12dc-11e9-8838-04048aee0408.png)

**Version Information**
 - OS: iOS 12.1.2 
 - Version 2.1.0

**Comment by Charlie9830** [comment]
Thanks for the Bug report.
I am currently rebuilding the UI for the Mobile app with a new Component Library. That should implicitly fix this issue. Update will be out in the coming weeks.
