### ISSUE TITLE
Task name edit dialogue is too small

### ISSUE THREAD

**Issue by RobH779** [Charlie9830/pounder#104]
**Describe the bug**
When you have a task selected and press enter to bring up the task name edit dialogue, it coms up in a very small box, often not being able to display the whole task.

**What were you doing at the time?**
Renaming a task by hitting 'enter'.

**Expected behavior**
Box needs to display a little larger to see the name in it's entirety.

**Screenshots**
![Screen Shot 2019-04-21 at 9 10 43 pm](https://user-images.githubusercontent.com/41365436/56469238-44870d80-647a-11e9-90e9-dc1f246acbfb.png)

**Version Information**
 - OS: Mac OSX 10.14.4
 - Version: 2.2.0

**Additional context**
This applies to both Shared and Personal projects.

**Comment by Charlie9830** [comment]
Fixed in
a07f2bc0c1cbf6188e033b34a5f98a44af4f63f1
