### ISSUE TITLE
ESC does not dismiss Task Info sidepane

### ISSUE THREAD

**Issue by RobH779** [Charlie9830/pounder#105]
**Describe the bug**
After double clicking on a Task to view additional info/edit details you can not return to the main app display by pressing ESC as you can with the edit name dialogue box. It requires you to click out of the pane to dismiss it. This interrupts keyboard workflow. Also it would be hand to have a keyboard shortcut to summon this pane as well.

**What were you doing at the time?**
Editing a task

**Expected behavior**
After being able to dismiss the Edit Task name dialogue with ESC I assumed the Task Info sidepane would behave similarly.

**Screenshots**
![Screen Shot 2019-04-21 at 9 22 26 pm](https://user-images.githubusercontent.com/41365436/56469304-94b29f80-647b-11e9-9b22-fd6c4be9538e.png)

**Version Information**
 - OS: Mac OS X 10.14.4
 - Version: 2.2.0

**Comment by Charlie9830** [comment]
Added in
0ed627e36d48601e0e5a45ea7612e922d539ff72
