### ISSUE TITLE
Bold Task List titles

### ISSUE THREAD

**Issue by RobH779** [Charlie9830/pounder#106]
** Describe the feature you would like to see added or modified **
Do you think the Task Lists would benefit from having **BOLD** text? Just to help them stand out a bit?

** Describe a use case for that feature **
Easier to differentiate from tasks in densely populated displays.

** Anything else you would like to add? **
I'm very sorry for how petty this feature request is XD

**Comment by Charlie9830** [comment]
I'm against Bold Titles as that is not recommended in the Material Design Spec. I do agree that the titles can get lost within a busy project. With that in mind I have added a background highlight to the toolbars to better differentiate them from the soup.

Added in.
5bb99a4ee6755babd3d75069acf7ad60808ff6bf
