### ISSUE TITLE
Add New Task in Task List menu

### ISSUE THREAD

**Issue by RobH779** [Charlie9830/pounder#107]
** Describe the feature you would like to see added or modified **
I think it would be good to have an 'Add New Task' option in the "three dots" menu. Or a + symbol in the title bar to allow users to add new tasks.

** Describe a use case for that feature **
While I personally use the keyboard CMD + N shortcut, the only other option to add a new task is the "+ Create Task" button in the top left corner of the app. While this does not affect my usability, it could be a bit disruptive for non-keyboard workflow users. (Unless you are pushing users towards keyboard workflows)

** Anything else you would like to add? **
This is by no means a definite request, more of a suggestion for thought. I personally enjoy how clean the interface is now and adding more buttons flies in the face of this.

**Comment by Charlie9830** [comment]
Added this as a button on the toolbar that only appears when hovering the mouse over the List toolbar.

334e1fe92bb44aa04ecb6282d0414ab0c9b1a12e
