### ISSUE TITLE
Project Name dropdown list

### ISSUE THREAD

**Issue by RobH779** [Charlie9830/pounder#108]
**Describe the feature you would like to see added or modified**
When the project selector sidepane is retracted it would be good if the Project Name became a dropdown list so you can change Projects without having to deploy the sidepane again  meaning you can work with the sidepane retracted for 95% of the time.

**Describe a use case for that feature**
Prevents having to deploy and retract the sidepane whenever you want to change Project and allows you to work with maximum screen realestate.

**Screenshot**
![Screen Shot 2019-04-21 at 10 21 35 pm](https://user-images.githubusercontent.com/41365436/56469975-d8110c00-6483-11e9-97d8-2ab47b563c7b.png)

**Comment by Charlie9830** [comment]
Added in 
2d4036bdf0866ce6a61aceb8dfc87a1534d699d2

![Screenshot](https://user-images.githubusercontent.com/11135679/56492441-2c24fa80-652f-11e9-8bc6-0a618941de6a.jpg)
