### ISSUE TITLE
Help Screen

### ISSUE THREAD

**Issue by Charlie9830** [Charlie9830/pounder#12]
Implement a Help screen inside App Settings Menu. Add a button on the main screen to shortcut to it.

**Comment by RobH779** [comment]
For what it's worth, Deputy has a dedicated Keyboard Shortcuts popup screen that is accessible from the main GUI without having to dig through settings menus to find. I find myself using it a lot for those "I think there's a button that does what all these mouse-clicks are doing" moments. 

Could be as simple as a drop-down menu from a ? symbol on the main page that has options such as: 
- Help
- Keyboard Shortcuts
- other help topics that might be top-tier worthy.

My two cents.

**Comment by Charlie9830** [comment]
I like that idea. I will most likely still implement it as a page within App Settings (Easier to add it to an existing window then create a brand new window for it). But I will drop a shortcut on the main screen to jump straight to it, like you can do with the Account Status Icon in the top right hand corner.
