### ISSUE TITLE
Auto-repeating tasks

### ISSUE THREAD

**Issue by RobH779** [Charlie9830/pounder#19]
What are your thoughts on implementing auto-repeating tasks that automatically uncomplete themselves or re-creates new instances of themselves on a user-definable timeframe?

Use case example is a Daily Checklist that is ready to be checked off everyday when you start work or a weekly/fortnightly inspection that pops back in to your list when it's time.

Again, just a thought. Not trying to blow this out into something it was never designed to be. I am, however, well known for 'feature surge' in projects 😝

**Comment by Charlie9830** [comment]
That's a great idea. I reckon I would implement it as a special type of List. Which "de-completes" it's child tasks after a set time and interval. Missed the boat on the next release, but I've added it to the Round 3 release milestone. Thanks for the idea.
