### ISSUE TITLE
Empty project name could coerce to "Untitled Project"

### ISSUE THREAD

**Issue by Charlie9830** [Charlie9830/pounder#2]

**Comment by RobH779** [comment]
I know this was my idea but this would remove the Secret List 'feature'! 😆 

![screen shot 2018-07-19 at 11 13 56 am](https://user-images.githubusercontent.com/41365436/42915711-daf069f2-8b44-11e8-973c-e8eb22927754.png)

**Comment by Charlie9830** [comment]
Implemented in Round 2 release.
