### ISSUE TITLE
New Task List resizing in default Project on app startup

### ISSUE THREAD

**Issue by RobH779** [Charlie9830/pounder#20]
**Description**
Upon opening Handball any new Task Lists in the default Project that were created on a different machine will display as tiny boxes until user changes to another Project. Upon returning to the default Project all Task Lists will be displayed correctly. This only occurs when new Task Lists have been created on machine A while machine B has the app closed, and only in the default Project. If both machines have the app open Task Lists are generated correctly, if new Task Lists are created in any other Projects they are displayed correctly upon changing to that Project.

**To Reproduce**
1. Close Handball on machine B.
2. On machine A, create a new Task List in the default Project.
3. Open Handball on machine B.
5. Change to another project and then back
6. Error fixed

**Expected behavior**
Project Layout is not resolving correctly on app startup but is working fine upon Project selection.

**Screenshots**

Figure 1: After creating new Task Lists on machine A, this is what you will see on startup of Handball on machine B
![screen shot 2018-07-19 at 10 58 51 am](https://user-images.githubusercontent.com/41365436/42915460-5e421b68-8b43-11e8-98bd-3e8fe8317679.png)

Figure 2: After clicking on another Project and then coming back to the default Project, the layout has resolved correctly.
![screen shot 2018-07-19 at 10 58 59 am](https://user-images.githubusercontent.com/41365436/42915483-823355b4-8b43-11e8-920d-143f69731503.png)

**Environment:**
 - Device: MacBook Air
 - OS: macOS High Sierra 10.13.6
 - Browser: Safari 11.1.2
 - Handball Version: 2.0.0 RC

**Comment by Charlie9830** [comment]
Oh boy.. This has led me to a bug that I believe is related to this. Handball is dumping several layouts a second into the database. You can tell if it is doing it if the "pl" sync indicator never turns green, even after several minutes of idleing. It is also chewing up memory as it is triggering pointless re renders several times a second. The UI Framework, React optimizes these updates, so I did not notice any problems until I added some debugging statements. I should have a new build that fixes this ready by later tonight.

**Comment by Charlie9830** [comment]
Issue should be fixed in Version 2.0.1-rc. Comment here if it occurs again.
