### ISSUE TITLE
Sort tasks Alphabetically

### ISSUE THREAD

**Issue by RobH779** [Charlie9830/pounder#25]
Add sort option for Task Lists to sort Tasks alphabetically.

Would be useful for grouping like tasks together by naming them accordingly:

**This list:**
- Princess Evacuation Drill
- Forum Deployment Version
- Plaza Deployment Version 
- Forum Evacuation Drill
- Princess Distribution Draft
- Plaza Evacuation Drill
- Princess Deployment Version

**Becomes this list:**
- Forum Deployment Version
- Forum Evacuation Drill
- Plaza Deployment Version 
- Plaza Evacuation Drill
- Princess Deployment Version
- Princess Distribution Draft
- Princess Evacuation Drill

**Comment by Charlie9830** [comment]
Huh... that thought never crossed my mind. Should be quick to implement so I'll add it into round 2 release. But I swear.. that's the last feature I'll creep into the next release.

**Comment by RobH779** [comment]
>that's the last feature I'll ~~creep~~ _surge_ into the next release.

FTFY
