### ISSUE TITLE
Handling of completed Tasks

### ISSUE THREAD

**Issue by Charlie9830** [Charlie9830/pounder#26]
The current implementation of holding Completed tasks is not going to scale. It is likely that the majority of Firestore reads are completed tasks. Two current options are.

### Option A
Auto purge completed tasks after a set period of time. eg 4 weeks.
### Option B

Only query Firestore for completed tasks in Task lists that have that setting applied. Nicer to the user, but harder to implement.

### Option C
Use a global toggle for showing or hiding Completed tasks. Auto reset this toggle to Hide after 5 minutes.
This requires the least Implementation overhead as it will only be toggling the one query between two states. This will break away from the Offline first implementation, but the added savings for the Database are likely worth it. It should also still be useful if the user wants to 'un-complete' an accidentally completed task, it should work even if the user is offline by only serving them the cached completed tasks.

**Comment by RobH779** [comment]
In Option B, would this mean that completed items are stored indefinitely but only shown when requested?

I like the idea of a "Show Completed Items" button that then turns into a "Hide Completed Items" button to encourage the user to hide them again when they are done to save Firestore reads.

**Comment by Charlie9830** [comment]
@RobH779  That's correct. They would be stored on the Database 'forever' (Until deleted via direct delete, task list delete, project delete or user account closure). But they would only be requested from the server when needed. This would mean though that whilst the user is Offline, showing completed tasks would fail, which is an unfortunate side effect which pushes against my concept of keeping the App as Offline Capable as possible.

I think though that I will have to bite the bullet and do it in order to keep the costs down.

**Comment by Charlie9830** [comment]
I've decided to go with Option C as it requires the least amount of complication to the existing code base, meaning less chance of critical bugs involving display of Tasks, which is kinda the whole Gimmick of the app.
