### ISSUE TITLE
Colour picker behaviour on Mobile.

### ISSUE THREAD

**Issue by RobH779** [Charlie9830/pounder#44]
**Describe the bug**
~Brightness buttons in colour picker can occasionally cause content to jump up.~ **(Likely the same issues as #45)** When sliding colour sliders, menu on bottom layer underneath also scrolls. Sometimes entire colour picker screen will move with colour slider. 

**Steps to reproduce**
In main menu, select a colour to change. When colour picker opens up, slide the colour sliders and see the menu scrolling underneath. Also after a while of scrolling you will notice the screen will occasionally slide with the slider. Pressing the brightness buttons on the left a whole bunch will sometimes cause the entire app content to jump up 20-30 pixels on each press although this one is very intermittent and hard to reproduce.

**Expected behavior**
Would expect the sliding action of the sliders not to affect the menu underneath or the entire page.

**Screenshots**
_Colour picker screen after pressing brightness buttons up and down a few times._
![img_7224](https://user-images.githubusercontent.com/41365436/43251370-10284720-9103-11e8-9a1e-f318bb4681a1.PNG)

**Version Information**
 - Model: iPhone 6S Plus 
 - OS: iOS 11.4.1
 - Version 2.0.2

**Additional context**

**Comment by Charlie9830** [comment]
Thanks for the report. This seems related to #45. 
When using the brightness buttons, does the content only jump when you tap them twice in quick succession? 

Additionally the content scrolling underneath the picker whilst you are dragging the color is a known issue with Safari, Safari doesn't yet support some crucial DOM methods that allow me to lock out scrolling functionality when the user is dragging on something interactive. Apple currently have no plans to implement these methods. I may look into shimming the behavior by extending the colour picker to fill the screen, then save the users scroll position when they open the color picker, then when the want to close it, programmatically force the scroll position back to where they started before closing the Picker.

Note: You can't work around this issue by using Chrome or Firefox for iOS instead. Apple do not allow any other manufacturer to run a Javascript Engine on iOS. What this means is, even if you are using Chrome, Firefox, Opera Mini or another browser, it's actually just a wrapper for safari.

**Comment by Charlie9830** [comment]
Another interesting thing to note, is that the icons used for the up and down arrows are the exact same files used to render the close arrow for the Task Metadata display.. But for some reason Safari doesn't render that icon on the metadata display.

**Comment by RobH779** [comment]
The brightness buttons do not require a double-tap to cause jumping. But also I have not been able to replicate that particular fault for a couple of days.

The workaround you suggest sounds like a massive pain but I agree with having the colour picker filling the screen at the very least. Then you wouldn't see the content scroll and probably wouldn't be a problem.

**Comment by Charlie9830** [comment]
Thanks for the extra info. The workaround "shouldn't" be too hard to implement. The Programmatic scroll behavior is already implemented in the Task list jump menu. The downward facing arrow on the project toolbar that auto scrolls you to the selected task list, and I'm sure I'm not the only one that has had to implement something like this before. Added to R3 Release.

**Comment by RobH779** [comment]
The "colour picker content jumping up" issue when pressing the brightness up/down buttons in the colour picker remains in mobile version 2.0.3 on iOS and is still intermittent and difficult to reproduce.

I was, however, able to capture this:

![img_7259](https://user-images.githubusercontent.com/41365436/44263101-f1144e00-a260-11e8-90b9-dcb080783055.PNG)

**Comment by Charlie9830** [comment]
Hard to say with certainty if it is releated to #45. I'll have another look at this issue for the next Major release. Thanks for the report.

**Comment by RobH779** [comment]
Also sometimes grabbing the slider knobs will cause the content to scroll up and down.

See the below screenshots:

![img_7260](https://user-images.githubusercontent.com/41365436/44296307-aeee1980-a2ff-11e8-89b0-91110f50924f.png)
Sliding down.

![img_7261](https://user-images.githubusercontent.com/41365436/44296308-b1507380-a2ff-11e8-85c1-909b5b791bad.png)
Sliding up.

**Comment by Charlie9830** [comment]
Thanks for the further issue. I'll look into this for the next Hotfix.

**Comment by Charlie9830** [comment]
Can't fix this until iOS Safari supports the 'touch-action: none' CSS Property.
