### ISSUE TITLE
Spelling/Content in Main Menu

### ISSUE THREAD

**Issue by RobH779** [Charlie9830/pounder#46]
Obviously not a priority but here are a few errors I came across in the documentation in the main menu.

**Spelling/Content Errors**
Welcome - Where is my data stored?:  "loose" should be "lose"
Welcome - Overview: "compatiable" should be "compatible"
Welcome - Overview: "efficent" should be "efficient"
Welcome - Why does this exist? - Project management apps: Repeated period after "haze machines.."
Welcome - Where is my data stored?: "Please see +++++++++++++++++ for more info on this."
Welcome - What's next? - Possible Future Monetization: "beleiver" should be "believer" 

Help - Command line arguements in Task names: "arguements" should be "arguments"
Help - Tips - Setting a due date: "arguements" should be "arguments"
Help - Tips - Setting a task as Important: "arguements" should be "arguments"
Help - Tips - Assigning a task to a project contributor: "assignemnt" should be "assignment"
Help - Tips - Task Arguments: "assingment" should be "assignment"
Help - Tips - Task Arguments: "hypen" should be "hyphen"
Help - Tips - Task Arguments - Assign To -a: "to much" should be "too much"

**Comment by Charlie9830** [comment]
Nice work. Thanks for that. I didn't really proof read any of it. Infact the +++++ is a placeholder for a link I never put in.
