### ISSUE TITLE
Text in Main Menu not tied to text colour variables

### ISSUE THREAD

**Issue by RobH779** [Charlie9830/pounder#48]
**Describe the bug**
Text throughout the Main Menu does not seem to be tied to any of the Text colour variables.
Also the hover colour in the Main Menu seems rogue.

**Version Information**
 - OS: macOS 10.13.6
 - Version 2.0.2

**Comment by Charlie9830** [comment]
Well spotted. Thanks for the report.
Added to R3 Release.
