### ISSUE TITLE
Sign up action button doesn't not change when User enters register mode. 

### ISSUE THREAD

**Issue by Charlie9830** [Charlie9830/pounder#7]
The sign up action button should toggle to "Sign In" when the user is in register mode.

**Comment by RobH779** [comment]
My thoughts on this were basically as follows:

When on Register screen: Display "Sign In to existing account" + 'Sign In' button

When on Login screen: Display "Register for new account" + 'Register' button

...or something to that effect. 😄

**Comment by RobH779** [comment]
Yes, agreed. My first thought was "This is busy, where should I look first?". 

But also I was pretty excited so that might have something to do with it 😆

**Comment by Charlie9830** [comment]
Cleaned up UI and added context sensitive states to Buttons and links.
