### ISSUE TITLE
Invite screen email text not tied to colour variable

### ISSUE THREAD

**Issue by RobH779** [Charlie9830/pounder#73]
**Describe the bug**
On the 'Invite' screen, the text in the email box that says "Email" doesn't seem to be tied to a colour variable. Any input text is appropriately coloured, just the example text isn't. Very low priority, but difficult to read in certain colour themes.

**Expected behavior**
I guess you'd expect it to be tied to one of the text colour variables.

**Screenshots**
![screen shot 2018-08-19 at 11 52 37 am](https://user-images.githubusercontent.com/41365436/44304698-810fe000-a3a6-11e8-89a7-6d6725511bf2.png)

**Version Information**
 - OS: MacOS 10.13.6
 - Version 2.0.3

**Comment by Charlie9830** [comment]
Thanks for the report. I'll look at this in the next hotfix.
