### ISSUE TITLE
'Select file' text should be using different colour variable

### ISSUE THREAD

**Issue by RobH779** [Charlie9830/pounder#74]
**General Feedback**
Not convinced this is a bug, more of a suggestion/question.

The 'Select file' text on the Database tab in Settings I feel should be using the Alternate Inactive Text Colour variable.

Otherwise the same text colour will be used on top of both the Primary Colour and Surface Colour, which I think will generally be inherently contrasting colours for most themes. I could be wrong about this though. 

The same goes for the Versions in About.

See below:
![screen shot 2018-08-19 at 11 55 11 am](https://user-images.githubusercontent.com/41365436/44304743-bbc64800-a3a7-11e8-8a98-5a20f589c78c.png)

**Comment by Charlie9830** [comment]
Likely not correctly tied to the color variables. I'll look at this in the next Hotfix.
