### ISSUE TITLE
Show completed tasks option - rogue q on Mobile

### ISSUE THREAD

**Issue by RobH779** [Charlie9830/pounder#75]
**Describe the bug**
When you select the three dots to toggle the appearance of completed tasks, there is a rogue black "q" at the end of the option.

**Screenshots**
![img_7263](https://user-images.githubusercontent.com/41365436/44305368-d7861a00-a3b8-11e8-8e9b-12d487e820a9.png)

**Version Information**
 - OS: iOS 11.4.1
 - Version 2.0.3

**Comment by Charlie9830** [comment]
Thanks for the report. I'll look at this in the next Hotfix.
