### ISSUE TITLE
'Show completed tasks' tooltips on Desktop and Mobile are different

### ISSUE THREAD

**Issue by RobH779** [Charlie9830/pounder#76]
**Describe the bug**
On mobile the tooltip is "Show completed tasks", on desktop the tooltip is "Show finished tasks".

**Expected behavior**
As these do the same thing, I would expect the nomenclature to be the same.

**Version Information**
 - OS: macOS 10.13.6, iOS 11.4.1
 - Version 2.0.3

**Comment by Charlie9830** [comment]
Thanks for the report. I'll look at this in the next Hotfix.
