### ISSUE TITLE
Black space at bottom of Task Lists on Mobile

### ISSUE THREAD

**Issue by RobH779** [Charlie9830/pounder#77]
**Describe the bug**
On Projects that don't have enough tasks to fill up the page, back space is generated to fill the gap between the bottom of the last Task List and the bottom of the screen. This does not seem to be tied to any colour variables and only exists in Projects less than a page long. 

**Expected behavior**
I guess this filler space should to be tied to either primary or background colours.

**Screenshots**
![img_7264](https://user-images.githubusercontent.com/41365436/44305443-9a228c00-a3ba-11e8-8a44-28cfab3c4180.png)

![img_7263 2](https://user-images.githubusercontent.com/41365436/44305441-94c54180-a3ba-11e8-881a-e60ecbee18fc.png)

**Version Information**
 - OS: iOS 11.4.1
 - Version 2.0.3

**Comment by Charlie9830** [comment]
You are correct the `<body> </body>` style isn't currently tied to any of the Color variables. I'll look at this in the next Hotfix.
