### ISSUE TITLE
Text input still possible with app locked 

### ISSUE THREAD

**Issue by RobH779** [Charlie9830/pounder#79]
**Describe the bug**
After locking the app, you can still enter text into the tasks by hitting enter, typing and then hitting enter again.

**Expected behavior**
I would expect locking the app to prevent any text entry from reaching the tasks.

**Version Information**
 - OS: macOS 10.13.6
 - Version 2.0.3

**Comment by Charlie9830** [comment]
Thanks for the report. Well spotted. I'll look at this in the next Hotfix.

**Comment by Charlie9830** [comment]
Non destructive operations are still possible when the App is Locked due to it being too complicated to try and block these, but modifications and destructive operations and blocked now.
