### ISSUE TITLE
Moving Task Lists between Projects

### ISSUE THREAD

**Issue by RobH779** [Charlie9830/pounder#89]
**Describe the feature you would like to see added or modified**
I would be interested in a method of moving Task Lists between Projects.

**Describe a use case for that feature**
For example, you have a private Project A "Day to Day Jobs" and a shared Project B "Special Event", you have assembled a list of devices that need repairing in Project A to be fixed over time, suddenly the scope of Project B changes and all these devices are to be repaired immediately utilising the team of people on the project. It would be easier to just move the list to Project B than re-enter all the tasks that need to be completed and delete them from Project A.

Also useful for if you put a list in a project and then later decide that it should be part of a different Project.

Another handy use would be doing a brain dump into a "Brain Dump" project and then dragging/moving the different lists to the appropriate Projects.

**Anything else you would like to add?**
Either Drag-and-Drop onto the destination Project or a "Move to:" dropdown box in the Task List settings panel would be suitable solutions for this.

**Comment by Charlie9830** [comment]
Thanks for the feature request. This has always been in the back of my mind and I've sort of already half built in the system to handle it. Just need to create the UI's for it. I will likely implement it via a Move To menu as Drag and Dropping of Task Lists will likely not be appreciated by the Layout system as it's already implementing it's own Drag and Drop system.
