### ISSUE TITLE
Scheduled backups & Manual backup options

### ISSUE THREAD

**Issue by RobH779** [Charlie9830/pounder#93]
**Describe the feature you would like to see added or modified**
I think it would be handy to implement an option to have backups scheduled to be created every 15/30/60/180 mins, every day, every week etc Also a button in Database tab in Settings that allows you to create a manual backup would also be good. Currently it seems like backups are only created upon closing the app, which can be problematic if you never close the app.

** Describe a use case for that feature **
You could have it set to backup every hour and then if something goes wrong you know you will only ever be an hour out of date when restoring from backup. Alternatively, after entering a lot of data you could do a manual backup to ensure its doesn't get lost.

**Comment by Charlie9830** [comment]
Hi @RobH779.
This feature is already somewhat implemented. In the Settings > General > Auto Backup interval. Set this to anything other than zero and the App will Auto backup by itself.

**Comment by RobH779** [comment]
Ah yes. Fair point.... *facepalm*
